# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'software_back.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1972, 988)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("\n"
"QWidget {\n"
"  color:#121212;\n"
"  background-color:#ffffff;\n"
"}")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-20, -10, 2281, 1091))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.widget.setFont(font)
        self.widget.setStyleSheet("\n"
"QWidget {\n"
"  background-color:#dcdcdc;\n"
"}")
        self.widget.setObjectName("widget")
        self.multizone_label = QtWidgets.QLabel(self.widget)
        self.multizone_label.setGeometry(QtCore.QRect(50, 70, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.multizone_label.setFont(font)
        self.multizone_label.setObjectName("multizone_label")
        self.CFD_label = QtWidgets.QLabel(self.widget)
        self.CFD_label.setGeometry(QtCore.QRect(1410, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CFD_label.setFont(font)
        self.CFD_label.setObjectName("CFD_label")
        self.TITLE = QtWidgets.QLabel(self.widget)
        self.TITLE.setGeometry(QtCore.QRect(820, 30, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.TITLE.setFont(font)
        self.TITLE.setStyleSheet("font: 75 15pt \"Times New Roman\";")
        self.TITLE.setObjectName("TITLE")
        self.cal_progressBar = QtWidgets.QProgressBar(self.widget)
        self.cal_progressBar.setGeometry(QtCore.QRect(710, 860, 671, 51))
        self.cal_progressBar.setStyleSheet("\n"
"QProgressBar {\n"
"  border: 1px solid #02246C;\n"
"  border-radius: 16px;\n"
"  color:#ffffff;\n"
"  font-size:32px;\n"
"  font-weight:bold;\n"
"  background-color:#010A20;\n"
"}\n"
" \n"
"QProgressBar::chunk {\n"
"    background-color: #02C3F7;\n"
"    border-radius: 16px;\n"
"}")
        self.cal_progressBar.setProperty("value", 24)
        self.cal_progressBar.setObjectName("cal_progressBar")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(-210, 630, 120, 80))
        self.groupBox.setObjectName("groupBox")
        self.toolBox = QtWidgets.QToolBox(self.widget)
        self.toolBox.setGeometry(QtCore.QRect(50, 130, 501, 861))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox {\n"
"    /*background:yellow;*/\n"
"    border:0px solid black;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    background:grey;\n"
"    border-radius:10px;\n"
"    color:white;\n"
"}\n"
"\n"
"/* 被选中的标签 */\n"
"QToolBox::tab:selected {\n"
"    /* 字体加粗,斜体 */\n"
"    font: bold italic;\n"
"    color:white;\n"
"}")
        self.toolBox.setLineWidth(1)
        self.toolBox.setObjectName("toolBox")
        self.M_ModelSelect = QtWidgets.QWidget()
        self.M_ModelSelect.setGeometry(QtCore.QRect(0, 0, 501, 709))
        self.M_ModelSelect.setStyleSheet("QWidget{\n"
"    background-color:white\n"
"}")
        self.M_ModelSelect.setObjectName("M_ModelSelect")
        self.mulitzone_input_label = QtWidgets.QLabel(self.M_ModelSelect)
        self.mulitzone_input_label.setGeometry(QtCore.QRect(20, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mulitzone_input_label.setFont(font)
        self.mulitzone_input_label.setObjectName("mulitzone_input_label")
        self.mulitzone_line = QtWidgets.QLineEdit(self.M_ModelSelect)
        self.mulitzone_line.setGeometry(QtCore.QRect(20, 70, 331, 31))
        self.mulitzone_line.setStyleSheet("QLineEdit{\n"
"background-color:white;\n"
"}")
        self.mulitzone_line.setObjectName("mulitzone_line")
        self.mulitzone_selectButton = QtWidgets.QPushButton(self.M_ModelSelect)
        self.mulitzone_selectButton.setGeometry(QtCore.QRect(370, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mulitzone_selectButton.setFont(font)
        self.mulitzone_selectButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.mulitzone_selectButton.setObjectName("mulitzone_selectButton")
        self.toolBox.addItem(self.M_ModelSelect, "")
        self.ParameteSet = QtWidgets.QWidget()
        self.ParameteSet.setGeometry(QtCore.QRect(0, 0, 501, 709))
        self.ParameteSet.setStyleSheet("QWidget{\n"
"    background-color:white\n"
"}")
        self.ParameteSet.setObjectName("ParameteSet")
        self.Room_parameter_label = QtWidgets.QLabel(self.ParameteSet)
        self.Room_parameter_label.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Room_parameter_label.setFont(font)
        self.Room_parameter_label.setObjectName("Room_parameter_label")
        self.modelica_Room_select_label = QtWidgets.QLabel(self.ParameteSet)
        self.modelica_Room_select_label.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.modelica_Room_select_label.setFont(font)
        self.modelica_Room_select_label.setObjectName("modelica_Room_select_label")
        self.Room_select_box = QtWidgets.QComboBox(self.ParameteSet)
        self.Room_select_box.setGeometry(QtCore.QRect(80, 60, 101, 31))
        self.Room_select_box.setObjectName("Room_select_box")
        self.Room_select_box.addItem("")
        self.Room_select_box.addItem("")
        self.Room_select_box.addItem("")
        self.Room_select_box.addItem("")
        self.Room_select_box.addItem("")
        self.Room_select_box.addItem("")
        self.Room_select_box.addItem("")
        self.Room_select_box.addItem("")
        self.Room_select_box.addItem("")
        self.Room_select_box.addItem("")
        self.Room_T_label = QtWidgets.QLabel(self.ParameteSet)
        self.Room_T_label.setGeometry(QtCore.QRect(190, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.Room_T_label.setFont(font)
        self.Room_T_label.setObjectName("Room_T_label")
        self.Room_T_line = QtWidgets.QLineEdit(self.ParameteSet)
        self.Room_T_line.setGeometry(QtCore.QRect(300, 60, 91, 31))
        self.Room_T_line.setObjectName("Room_T_line")
        self.Room_T_Button = QtWidgets.QPushButton(self.ParameteSet)
        self.Room_T_Button.setGeometry(QtCore.QRect(400, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Room_T_Button.setFont(font)
        self.Room_T_Button.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.Room_T_Button.setObjectName("Room_T_Button")
        self.Door_Paremeter_label = QtWidgets.QLabel(self.ParameteSet)
        self.Door_Paremeter_label.setGeometry(QtCore.QRect(10, 130, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Door_Paremeter_label.setFont(font)
        self.Door_Paremeter_label.setObjectName("Door_Paremeter_label")
        self.door_select_label = QtWidgets.QLabel(self.ParameteSet)
        self.door_select_label.setGeometry(QtCore.QRect(10, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(10)
        self.door_select_label.setFont(font)
        self.door_select_label.setObjectName("door_select_label")
        self.door_select_box = QtWidgets.QComboBox(self.ParameteSet)
        self.door_select_box.setGeometry(QtCore.QRect(90, 170, 131, 31))
        self.door_select_box.setObjectName("door_select_box")
        self.door_select_box.addItem("")
        self.door_select_box.addItem("")
        self.door_select_box.addItem("")
        self.door_select_box.addItem("")
        self.door_select_box.addItem("")
        self.door_select_box.addItem("")
        self.door_select_box.addItem("")
        self.door_select_box.addItem("")
        self.door_select_box.addItem("")
        self.Door_leakage_label = QtWidgets.QLabel(self.ParameteSet)
        self.Door_leakage_label.setGeometry(QtCore.QRect(10, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.Door_leakage_label.setFont(font)
        self.Door_leakage_label.setObjectName("Door_leakage_label")
        self.Door_leakage_line = QtWidgets.QLineEdit(self.ParameteSet)
        self.Door_leakage_line.setGeometry(QtCore.QRect(130, 220, 91, 31))
        self.Door_leakage_line.setObjectName("Door_leakage_line")
        self.cd_label = QtWidgets.QLabel(self.ParameteSet)
        self.cd_label.setGeometry(QtCore.QRect(10, 280, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.cd_label.setFont(font)
        self.cd_label.setObjectName("cd_label")
        self.cd_line = QtWidgets.QLineEdit(self.ParameteSet)
        self.cd_line.setGeometry(QtCore.QRect(130, 280, 91, 31))
        self.cd_line.setObjectName("cd_line")
        self.m_label = QtWidgets.QLabel(self.ParameteSet)
        self.m_label.setGeometry(QtCore.QRect(10, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(10)
        self.m_label.setFont(font)
        self.m_label.setObjectName("m_label")
        self.m_line = QtWidgets.QLineEdit(self.ParameteSet)
        self.m_line.setGeometry(QtCore.QRect(130, 340, 91, 31))
        self.m_line.setObjectName("m_line")
        self.doorButton = QtWidgets.QPushButton(self.ParameteSet)
        self.doorButton.setGeometry(QtCore.QRect(240, 340, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.doorButton.setFont(font)
        self.doorButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.doorButton.setObjectName("doorButton")
        self.filter_parameter_label = QtWidgets.QLabel(self.ParameteSet)
        self.filter_parameter_label.setGeometry(QtCore.QRect(10, 410, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filter_parameter_label.setFont(font)
        self.filter_parameter_label.setObjectName("filter_parameter_label")
        self.curve_a_label_2 = QtWidgets.QLabel(self.ParameteSet)
        self.curve_a_label_2.setGeometry(QtCore.QRect(10, 450, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.curve_a_label_2.setFont(font)
        self.curve_a_label_2.setObjectName("curve_a_label_2")
        self.Cleaner_selectbox = QtWidgets.QComboBox(self.ParameteSet)
        self.Cleaner_selectbox.setGeometry(QtCore.QRect(110, 450, 101, 31))
        self.Cleaner_selectbox.setObjectName("Cleaner_selectbox")
        self.Cleaner_selectbox.addItem("")
        self.curve_a_label = QtWidgets.QLabel(self.ParameteSet)
        self.curve_a_label.setGeometry(QtCore.QRect(10, 500, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.curve_a_label.setFont(font)
        self.curve_a_label.setObjectName("curve_a_label")
        self.curve_a_line = QtWidgets.QLineEdit(self.ParameteSet)
        self.curve_a_line.setGeometry(QtCore.QRect(140, 500, 91, 31))
        self.curve_a_line.setObjectName("curve_a_line")
        self.curve_Button = QtWidgets.QPushButton(self.ParameteSet)
        self.curve_Button.setGeometry(QtCore.QRect(260, 520, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.curve_Button.setFont(font)
        self.curve_Button.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.curve_Button.setObjectName("curve_Button")
        self.curve_b_label = QtWidgets.QLabel(self.ParameteSet)
        self.curve_b_label.setGeometry(QtCore.QRect(10, 540, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.curve_b_label.setFont(font)
        self.curve_b_label.setObjectName("curve_b_label")
        self.curve_b_line = QtWidgets.QLineEdit(self.ParameteSet)
        self.curve_b_line.setGeometry(QtCore.QRect(140, 550, 91, 31))
        self.curve_b_line.setObjectName("curve_b_line")
        self.toolBox.addItem(self.ParameteSet, "")
        self.TimeParameter = QtWidgets.QWidget()
        self.TimeParameter.setGeometry(QtCore.QRect(0, 0, 501, 709))
        self.TimeParameter.setStyleSheet("QWidget{\n"
"    background-color:white\n"
"}")
        self.TimeParameter.setObjectName("TimeParameter")
        self.time_label = QtWidgets.QLabel(self.TimeParameter)
        self.time_label.setGeometry(QtCore.QRect(20, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.endtime_label = QtWidgets.QLabel(self.TimeParameter)
        self.endtime_label.setGeometry(QtCore.QRect(20, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.endtime_label.setFont(font)
        self.endtime_label.setObjectName("endtime_label")
        self.endtime_line = QtWidgets.QLineEdit(self.TimeParameter)
        self.endtime_line.setGeometry(QtCore.QRect(150, 90, 131, 31))
        self.endtime_line.setObjectName("endtime_line")
        self.endtimeButton = QtWidgets.QPushButton(self.TimeParameter)
        self.endtimeButton.setGeometry(QtCore.QRect(310, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.endtimeButton.setFont(font)
        self.endtimeButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.endtimeButton.setObjectName("endtimeButton")
        self.interval_label = QtWidgets.QLabel(self.TimeParameter)
        self.interval_label.setGeometry(QtCore.QRect(20, 250, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.interval_label.setFont(font)
        self.interval_label.setObjectName("interval_label")
        self.interval_line = QtWidgets.QLineEdit(self.TimeParameter)
        self.interval_line.setGeometry(QtCore.QRect(150, 250, 131, 31))
        self.interval_line.setObjectName("interval_line")
        self.intervalButton = QtWidgets.QPushButton(self.TimeParameter)
        self.intervalButton.setGeometry(QtCore.QRect(310, 250, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.intervalButton.setFont(font)
        self.intervalButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.intervalButton.setObjectName("intervalButton")
        self.dt_button = QtWidgets.QPushButton(self.TimeParameter)
        self.dt_button.setGeometry(QtCore.QRect(310, 410, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dt_button.setFont(font)
        self.dt_button.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.dt_button.setObjectName("dt_button")
        self.label_6 = QtWidgets.QLabel(self.TimeParameter)
        self.label_6.setGeometry(QtCore.QRect(20, 410, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dt_line = QtWidgets.QLineEdit(self.TimeParameter)
        self.dt_line.setGeometry(QtCore.QRect(150, 410, 131, 31))
        self.dt_line.setObjectName("dt_line")
        self.toolBox.addItem(self.TimeParameter, "")
        self.SimulateSet = QtWidgets.QWidget()
        self.SimulateSet.setGeometry(QtCore.QRect(0, 0, 501, 709))
        self.SimulateSet.setStyleSheet("QWidget{\n"
"    background-color:white\n"
"}")
        self.SimulateSet.setObjectName("SimulateSet")
        self.label = QtWidgets.QLabel(self.SimulateSet)
        self.label.setGeometry(QtCore.QRect(10, 190, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.MFEXD1 = QtWidgets.QLineEdit(self.SimulateSet)
        self.MFEXD1.setGeometry(QtCore.QRect(20, 260, 281, 41))
        self.MFEXD1.setObjectName("MFEXD1")
        self.MFEXDconfirm = QtWidgets.QPushButton(self.SimulateSet)
        self.MFEXDconfirm.setGeometry(QtCore.QRect(320, 270, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.MFEXDconfirm.setFont(font)
        self.MFEXDconfirm.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.MFEXDconfirm.setObjectName("MFEXDconfirm")
        self.label_2 = QtWidgets.QLabel(self.SimulateSet)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.SimulateSet)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.toolBox.addItem(self.SimulateSet, "")
        self.simstartButton = QtWidgets.QPushButton(self.widget)
        self.simstartButton.setGeometry(QtCore.QRect(560, 860, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.simstartButton.setFont(font)
        self.simstartButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.simstartButton.setObjectName("simstartButton")
        self.multi_result_path_label = QtWidgets.QLabel(self.widget)
        self.multi_result_path_label.setGeometry(QtCore.QRect(560, 930, 731, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.multi_result_path_label.setFont(font)
        self.multi_result_path_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.multi_result_path_label.setObjectName("multi_result_path_label")
        self.Fluent_tool = QtWidgets.QToolBox(self.widget)
        self.Fluent_tool.setGeometry(QtCore.QRect(1410, 130, 501, 861))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.Fluent_tool.setFont(font)
        self.Fluent_tool.setStyleSheet("QToolBox {\n"
"    /*background:yellow;*/\n"
"    border:0px solid black;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    background:grey;\n"
"    border-radius:10px;\n"
"    color:white;\n"
"}\n"
"\n"
"/* 被选中的标签 */\n"
"QToolBox::tab:selected {\n"
"    /* 字体加粗,斜体 */\n"
"    font: bold italic;\n"
"    color:white;\n"
"}")
        self.Fluent_tool.setObjectName("Fluent_tool")
        self.MeshSelect = QtWidgets.QWidget()
        self.MeshSelect.setGeometry(QtCore.QRect(0, 0, 501, 709))
        self.MeshSelect.setStyleSheet("QWidget{\n"
"    background-color:white;\n"
"}")
        self.MeshSelect.setObjectName("MeshSelect")
        self.CFD_mesh_label = QtWidgets.QLabel(self.MeshSelect)
        self.CFD_mesh_label.setGeometry(QtCore.QRect(20, 60, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.CFD_mesh_label.setFont(font)
        self.CFD_mesh_label.setObjectName("CFD_mesh_label")
        self.mesh_input_line = QtWidgets.QLineEdit(self.MeshSelect)
        self.mesh_input_line.setGeometry(QtCore.QRect(20, 110, 141, 31))
        self.mesh_input_line.setObjectName("mesh_input_line")
        self.MeshButton = QtWidgets.QPushButton(self.MeshSelect)
        self.MeshButton.setGeometry(QtCore.QRect(180, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.MeshButton.setFont(font)
        self.MeshButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.MeshButton.setObjectName("MeshButton")
        self.CAS_label_2 = QtWidgets.QLabel(self.MeshSelect)
        self.CAS_label_2.setGeometry(QtCore.QRect(20, 200, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.CAS_label_2.setFont(font)
        self.CAS_label_2.setObjectName("CAS_label_2")
        self.casButton = QtWidgets.QPushButton(self.MeshSelect)
        self.casButton.setGeometry(QtCore.QRect(140, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.casButton.setFont(font)
        self.casButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.casButton.setObjectName("casButton")
        self.cas_input_line_2 = QtWidgets.QLineEdit(self.MeshSelect)
        self.cas_input_line_2.setGeometry(QtCore.QRect(20, 260, 101, 31))
        self.cas_input_line_2.setObjectName("cas_input_line_2")
        self.UDF_label_4 = QtWidgets.QLabel(self.MeshSelect)
        self.UDF_label_4.setGeometry(QtCore.QRect(20, 370, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.UDF_label_4.setFont(font)
        self.UDF_label_4.setObjectName("UDF_label_4")
        self.udfButton = QtWidgets.QPushButton(self.MeshSelect)
        self.udfButton.setGeometry(QtCore.QRect(400, 420, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.udfButton.setFont(font)
        self.udfButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.udfButton.setObjectName("udfButton")
        self.udf_input_line_4 = QtWidgets.QLineEdit(self.MeshSelect)
        self.udf_input_line_4.setGeometry(QtCore.QRect(20, 420, 361, 31))
        self.udf_input_line_4.setObjectName("udf_input_line_4")
        self.dpm_label = QtWidgets.QLabel(self.MeshSelect)
        self.dpm_label.setGeometry(QtCore.QRect(290, 100, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dpm_label.setFont(font)
        self.dpm_label.setObjectName("dpm_label")
        self.dpm_checkbox = QtWidgets.QCheckBox(self.MeshSelect)
        self.dpm_checkbox.setGeometry(QtCore.QRect(410, 110, 71, 31))
        self.dpm_checkbox.setObjectName("dpm_checkbox")
        self.Fluent_tool.addItem(self.MeshSelect, "")
        self.BoundaryCondition = QtWidgets.QWidget()
        self.BoundaryCondition.setGeometry(QtCore.QRect(0, 0, 501, 709))
        self.BoundaryCondition.setStyleSheet("QWidget{\n"
"    background-color:white\n"
"}")
        self.BoundaryCondition.setObjectName("BoundaryCondition")
        self.boundary_VlineEdit = QtWidgets.QLineEdit(self.BoundaryCondition)
        self.boundary_VlineEdit.setGeometry(QtCore.QRect(180, 210, 101, 31))
        self.boundary_VlineEdit.setObjectName("boundary_VlineEdit")
        self.boundary_TlineEdit = QtWidgets.QLineEdit(self.BoundaryCondition)
        self.boundary_TlineEdit.setGeometry(QtCore.QRect(180, 130, 101, 31))
        self.boundary_TlineEdit.setObjectName("boundary_TlineEdit")
        self.Boundary_con_label = QtWidgets.QLabel(self.BoundaryCondition)
        self.Boundary_con_label.setGeometry(QtCore.QRect(20, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Boundary_con_label.setFont(font)
        self.Boundary_con_label.setObjectName("Boundary_con_label")
        self.Boundary_Vlabel = QtWidgets.QLabel(self.BoundaryCondition)
        self.Boundary_Vlabel.setGeometry(QtCore.QRect(20, 200, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Boundary_Vlabel.setFont(font)
        self.Boundary_Vlabel.setObjectName("Boundary_Vlabel")
        self.Boundary_Tlabel = QtWidgets.QLabel(self.BoundaryCondition)
        self.Boundary_Tlabel.setGeometry(QtCore.QRect(20, 140, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Boundary_Tlabel.setFont(font)
        self.Boundary_Tlabel.setObjectName("Boundary_Tlabel")
        self.Boundary_select = QtWidgets.QComboBox(self.BoundaryCondition)
        self.Boundary_select.setGeometry(QtCore.QRect(180, 60, 101, 31))
        self.Boundary_select.setObjectName("Boundary_select")
        self.Boundary_select.addItem("")
        self.Boundary_select.addItem("")
        self.Boundary_select.addItem("")
        self.Boundary_select.addItem("")
        self.Boundary_select.addItem("")
        self.Boundary_select.addItem("")
        self.Boundary_select.addItem("")
        self.Boundary_select.addItem("")
        self.Boundary_select.addItem("")
        self.NegitiveP = QtWidgets.QCheckBox(self.BoundaryCondition)
        self.NegitiveP.setGeometry(QtCore.QRect(320, 50, 141, 51))
        self.NegitiveP.setObjectName("NegitiveP")
        self.boundaryInputButton = QtWidgets.QPushButton(self.BoundaryCondition)
        self.boundaryInputButton.setGeometry(QtCore.QRect(320, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boundaryInputButton.setFont(font)
        self.boundaryInputButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.boundaryInputButton.setObjectName("boundaryInputButton")
        self.set_status_label = QtWidgets.QLabel(self.BoundaryCondition)
        self.set_status_label.setGeometry(QtCore.QRect(20, 280, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.set_status_label.setFont(font)
        self.set_status_label.setObjectName("set_status_label")
        self.Fluent_tool.addItem(self.BoundaryCondition, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 501, 709))
        self.page.setStyleSheet("QWidget{\n"
"    background-color:white\n"
"}")
        self.page.setObjectName("page")
        self.FMEXD1 = QtWidgets.QLineEdit(self.page)
        self.FMEXD1.setGeometry(QtCore.QRect(40, 170, 241, 41))
        self.FMEXD1.setObjectName("FMEXD1")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(40, 80, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.FMEXDconfirm = QtWidgets.QPushButton(self.page)
        self.FMEXDconfirm.setGeometry(QtCore.QRect(310, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.FMEXDconfirm.setFont(font)
        self.FMEXDconfirm.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.FMEXDconfirm.setObjectName("FMEXDconfirm")
        self.Fluent_tool.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 501, 709))
        self.page_2.setStyleSheet("QWidget{\n"
"    background-color:white\n"
"}")
        self.page_2.setObjectName("page_2")
        self.cd_file_downloadButton = QtWidgets.QPushButton(self.page_2)
        self.cd_file_downloadButton.setGeometry(QtCore.QRect(340, 180, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cd_file_downloadButton.setFont(font)
        self.cd_file_downloadButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:grey;\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:black;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.cd_file_downloadButton.setObjectName("cd_file_downloadButton")
        self.cas_line = QtWidgets.QLineEdit(self.page_2)
        self.cas_line.setGeometry(QtCore.QRect(20, 140, 281, 41))
        self.cas_line.setObjectName("cas_line")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.dat_line = QtWidgets.QLineEdit(self.page_2)
        self.dat_line.setGeometry(QtCore.QRect(20, 220, 281, 41))
        self.dat_line.setObjectName("dat_line")
        self.Fluent_tool.addItem(self.page_2, "")
        self.Reslut_label = QtWidgets.QLabel(self.widget)
        self.Reslut_label.setGeometry(QtCore.QRect(580, 220, 691, 561))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.Reslut_label.setFont(font)
        self.Reslut_label.setObjectName("Reslut_label")

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(3)
        self.Fluent_tool.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.multizone_label.setText(_translate("Form", "Modelica"))
        self.CFD_label.setText(_translate("Form", "CFD"))
        self.TITLE.setText(_translate("Form", "Modelica-Fluent联合模拟软件"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.mulitzone_input_label.setText(_translate("Form", "多区模型输入"))
        self.mulitzone_selectButton.setText(_translate("Form", "浏览"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.M_ModelSelect), _translate("Form", "模型选择"))
        self.Room_parameter_label.setText(_translate("Form", "房间参数"))
        self.modelica_Room_select_label.setText(_translate("Form", "房间选择"))
        self.Room_select_box.setItemText(0, _translate("Form", "..."))
        self.Room_select_box.setItemText(1, _translate("Form", "fixedTemperature1"))
        self.Room_select_box.setItemText(2, _translate("Form", "fixedTemperature2"))
        self.Room_select_box.setItemText(3, _translate("Form", "fixedTemperature3"))
        self.Room_select_box.setItemText(4, _translate("Form", "fixedTemperature4"))
        self.Room_select_box.setItemText(5, _translate("Form", "fixedTemperature5"))
        self.Room_select_box.setItemText(6, _translate("Form", "fixedTemperature6"))
        self.Room_select_box.setItemText(7, _translate("Form", "fixedTemperature7"))
        self.Room_select_box.setItemText(8, _translate("Form", "fixedTemperature8"))
        self.Room_select_box.setItemText(9, _translate("Form", "fixedTemperature11"))
        self.Room_T_label.setText(_translate("Form", "房间温度T(K)"))
        self.Room_T_Button.setText(_translate("Form", "导入"))
        self.Door_Paremeter_label.setText(_translate("Form", "门的参数"))
        self.door_select_label.setText(_translate("Form", "通道选择"))
        self.door_select_box.setItemText(0, _translate("Form", "..."))
        self.door_select_box.setItemText(1, _translate("Form", "dooEC1"))
        self.door_select_box.setItemText(2, _translate("Form", "dooEC2"))
        self.door_select_box.setItemText(3, _translate("Form", "dooEC3"))
        self.door_select_box.setItemText(4, _translate("Form", "dooEC4"))
        self.door_select_box.setItemText(5, _translate("Form", "dooFB1"))
        self.door_select_box.setItemText(6, _translate("Form", "dooFB2"))
        self.door_select_box.setItemText(7, _translate("Form", "dooFE1"))
        self.door_select_box.setItemText(8, _translate("Form", "dooFE2"))
        self.Door_leakage_label.setText(_translate("Form", "门的缝隙L(m2)"))
        self.cd_label.setText(_translate("Form", "流量系数cd"))
        self.m_label.setText(_translate("Form", "流动指数m"))
        self.doorButton.setText(_translate("Form", "导入"))
        self.filter_parameter_label.setText(_translate("Form", "过滤器的参数(Q-ΔP)"))
        self.curve_a_label_2.setText(_translate("Form", "过滤器选择"))
        self.Cleaner_selectbox.setItemText(0, _translate("Form", "..."))
        self.curve_a_label.setText(_translate("Form", "特征曲线系数a"))
        self.curve_Button.setText(_translate("Form", "导入"))
        self.curve_b_label.setText(_translate("Form", "特征曲线系数b"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ParameteSet), _translate("Form", "参数设置"))
        self.time_label.setText(_translate("Form", "时间参数"))
        self.endtime_label.setText(_translate("Form", "终止时间(s)"))
        self.endtimeButton.setText(_translate("Form", "确定"))
        self.interval_label.setText(_translate("Form", "交换时间"))
        self.intervalButton.setText(_translate("Form", "确定"))
        self.dt_button.setText(_translate("Form", "确定"))
        self.label_6.setText(_translate("Form", "推进步长"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.TimeParameter), _translate("Form", "时间参数设置"))
        self.label.setText(_translate("Form", "输入交换数据表达式"))
        self.MFEXDconfirm.setText(_translate("Form", "确定"))
        self.label_2.setText(_translate("Form", "输入从Modelica导入Fluent的数据"))
        self.label_3.setText(_translate("Form", "例如 SupplyAir.T_in inlet.T;..."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.SimulateSet), _translate("Form", "模拟设置"))
        self.simstartButton.setText(_translate("Form", "开始耦合"))
        self.multi_result_path_label.setText(_translate("Form", "模拟状态"))
        self.CFD_mesh_label.setText(_translate("Form", "Mesh文件选择"))
        self.MeshButton.setText(_translate("Form", "浏览"))
        self.CAS_label_2.setText(_translate("Form", "cas文件选择"))
        self.casButton.setText(_translate("Form", "浏览"))
        self.UDF_label_4.setText(_translate("Form", "UDF选择"))
        self.udfButton.setText(_translate("Form", "加载"))
        self.dpm_label.setText(_translate("Form", "开启dpm模型"))
        self.dpm_checkbox.setText(_translate("Form", "open"))
        self.Fluent_tool.setItemText(self.Fluent_tool.indexOf(self.MeshSelect), _translate("Form", "网格模型选择"))
        self.Boundary_con_label.setText(_translate("Form", "边界条件"))
        self.Boundary_Vlabel.setText(_translate("Form", "送风速度(m/s)"))
        self.Boundary_Tlabel.setText(_translate("Form", "送风温度(℃)"))
        self.Boundary_select.setItemText(0, _translate("Form", "..."))
        self.Boundary_select.setItemText(1, _translate("Form", "ex-wall"))
        self.Boundary_select.setItemText(2, _translate("Form", "source"))
        self.Boundary_select.setItemText(3, _translate("Form", "wall_evaporator"))
        self.Boundary_select.setItemText(4, _translate("Form", "wall_pipe"))
        self.Boundary_select.setItemText(5, _translate("Form", "wall_stainless"))
        self.Boundary_select.setItemText(6, _translate("Form", "wall_tower"))
        self.Boundary_select.setItemText(7, _translate("Form", "inlet"))
        self.Boundary_select.setItemText(8, _translate("Form", "outlet"))
        self.NegitiveP.setText(_translate("Form", "切换负压房间"))
        self.boundaryInputButton.setText(_translate("Form", "导入"))
        self.set_status_label.setText(_translate("Form", "设置状态"))
        self.Fluent_tool.setItemText(self.Fluent_tool.indexOf(self.BoundaryCondition), _translate("Form", "边界条件"))
        self.label_4.setText(_translate("Form", "例如 inlet.T SupplyAir.T_in;..."))
        self.label_5.setText(_translate("Form", "输入从Fluent导入Modelica的数据"))
        self.FMEXDconfirm.setText(_translate("Form", "确定"))
        self.Fluent_tool.setItemText(self.Fluent_tool.indexOf(self.page), _translate("Form", "数据交换设置"))
        self.cd_file_downloadButton.setText(_translate("Form", "下载"))
        self.label_7.setText(_translate("Form", "保存DAT，CAS文件"))
        self.Fluent_tool.setItemText(self.Fluent_tool.indexOf(self.page_2), _translate("Form", "结果保存"))
        self.Reslut_label.setText(_translate("Form", "结果将在此处展示"))
